#!/usr/bin/env python3
"""
Script to propagate enriched 'cotidiano' content from Spanish to all languages
"""
import json
import os

# Spanish source content (enriched)
spanish_cotidiano = {
    0: "El Dispositor de la Innovación y la Mente de Principiante. En la psicología práctica, El Loco nos invita a adoptar la 'Shoshin' (Mente de Principiante) para curar la parálisis por análisis. No es solo emprender un negocio, es la capacidad de operar con Confianza Radical ante la incertidumbre total. Representa el permiso interno para cometer errores como método de aprendizaje iterativo. En tu día a día, aparece cuando la lógica convencional te dice 'detente', pero tu intuición grita 'salta'. Es el antídoto contra el cinismo adulto; nos recuerda que el juego y la curiosidad son herramientas de alta adaptación evolutiva, no distracciones infantiles.",
    1: "El Tecnólogo y la Autoeficacia. Psicológicamente, este arcano activa tu Función Ejecutiva: la capacidad de organizar, planificar y ejecutar. Es el estado de 'Deep Work' (Trabajo Profundo) donde la habilidad coincide con el desafío, generando el Estado de Flujo. Aquí no hay milagros; hay Manifestación Consciente a través de la disciplina técnica. En tus relaciones y carrera, el Mago pregunta: '¿Tienes las herramientas adecuadas para lo que quieres construir?'. Nos enseña que la verdadera magia es la atención dirigida; donde pones tu foco, pones tu realidad.",
    2: "El Analista de Datos y la Intuición Estratégica. En la era de la información, la Sacerdotisa es el arquetipo de la Intuición Estratégica. No es magia, es el reconocimiento de patrones subconscientes. Aparece cuando 'sabes' que un proyecto fallará aunque los números digan lo contrario. Nos enseña a confiar en las 'corazonadas' como datos procesados a alta velocidad por el cerebro límbico. Es el antídoto contra la saturación informativa; su lección es el Silencio Activo: retirarse del ruido para escuchar la verdad interna.",
    3: "La Creatividad Fértil y el Autocuidado. La Emperatriz nos alerta contra la 'Cultura del Burnout'. Ella enseña que el descanso no es pereza, sino una parte vital del ciclo productivo. Es la defensora del Placer Consciente. En el trabajo, representa la creatividad orgánica: las ideas que necesitan gestarse sin presión. Si te sientes estancado, la Emperatriz dice: 'Deja de empujar y empieza a nutrir'. Conéctate con la belleza o la naturaleza para resetear tu sistema nervioso.",
    4: "El Liderazgo y la Estructura Interior. El Emperador no es solo 'el jefe', es tu propia capacidad de autogobierno. Representa la Disciplina Estoica. Aparece para preguntar: '¿Eres esclavo de tus impulsos o rey de tu propia mente?'. En la vida moderna, es la creación de sistemas y hábitos atómicos que sostienen el éxito a largo plazo. Nos enseña a decir 'No' para proteger nuestro tiempo y energía. Su lección es que la verdadera libertad requiere estructura.",
    5: "El Mentor y la Pertenencia. El Hierofante aborda nuestra necesidad psicológica de pertenencia y sentido compartido. Es el antídoto contra el nihilismo individualista. En la práctica, te invita a buscar un mentor o una comunidad de práctica. Advierte contra el 'Pensamiento de Grupo' (Groupthink) pero valora la Tradición como una biblioteca de soluciones probadas por el tiempo. Te pregunta: '¿En qué crees y con quién compartes esa creencia?'.",
    6: "La Encrucijada de Valores y la Inteligencia Emocional. Los Enamorados plantean el dilema moderno del 'Costo de Oportunidad'. Elegir A significa necesariamente matar B. Psicológicamente, es la prueba de madurez: ¿Eliges basándote en la Gratificación Instantánea o en tus Valores Nucleares? En las relaciones, advierte contra la proyección: ver al otro como un salvador o un demonio en lugar de un ser humano. Nos impulsa a integrar cabeza y corazón para tomar decisiones irreversibles.",
    7: "El Enfoque Láser y la Máscara Social. El Carro es el arquetipo del 'Alto Rendimiento'. Nos habla de la capacidad de compartimentar las emociones para lograr un objetivo ('Ponerse la armadura para ir al trabajo'). Sin embargo, advierte sobre el peligro de identificarse demasiado con el rol social (La Persona). Es la victoria mediante la disciplina férrea, pero recuerda: un carro no se puede conducir para siempre; el guerrero eventualmente necesita descansar.",
    8: "La Resiliencia y el Poder Blando. La Fuerza nos enseña sobre la Inteligencia Emocional y la autorregulación. En el liderazgo moderno, es el 'Soft Power': la capacidad de influir sin forzar. Es vital para manejar la Ira Productiva y convertir el conflicto en combustible creativo. Si te sientes agotado por reprimir tus emociones, La Fuerza te invita a dialogar con tu 'bestia interna' en lugar de enjaularla.",
    9: "La Introspección Radical y el Analista Interno. El Ermitaño te invita a desconectar para reconectar. Es el arquetipo de la 'Dieta Digital' o el Retiro de Silencio. Aparece cuando necesitas filtrar el ruido externo para escuchar tu propia voz. Psicológicamente, representa la capacidad de estar solo sin sentirse solitario. Valida la necesidad de alejarse de la masa para encontrar la propia verdad.",
    10: "La Locus de Control y la Adaptabilidad. La Rueda nos enseña sobre la Resiliencia ante el cambio. En psicología, se trata de entender tu 'Locus de Control': ¿Te enfocas en lo que puedes cambiar o te quejas de lo que no puedes? Es el arcano del Estoicismo. En finanzas y carrera, representa la volatilidad del mercado. La lección es: no te apegues al éxito ni te definas por el fracasso, ambas son fases del ciclo."
}

# Translations for all languages
translations = {
    "en": {
        0: "The Innovation Disposer and Beginner's Mind. In practical psychology, The Fool invites us to adopt 'Shoshin' (Beginner's Mind) to cure paralysis by analysis. It is not just about starting a business, it is the ability to operate with Radical Confidence in the face of total uncertainty. It represents the internal permission to make mistakes as an iterative learning method. In your daily life, it appears when conventional logic tells you to 'stop', but your intuition screams 'jump'. It is the antidote to adult cynicism; reminding us that play and curiosity are tools of high evolutionary adaptation, not childish distractions.",
        1: "The Technologist and Self-Efficacy. Psychologically, this arcanum activates your Executive Function: the ability to organize, plan, and execute. It is the state of 'Deep Work' where skill meets challenge, generating the Flow State. Here there are no miracles; there is Conscious Manifestation through technical discipline. In your relationships and career, The Magician asks: 'Do you have the right tools for what you want to build?' It teaches us that true magic is directed attention; where you place your focus, you place your reality.",
        2: "The Data Analyst and Strategic Intuition. In the information age, the High Priestess is the archetype of Strategic Intuition. It is not magic; it is the recognition of subconscious patterns. She appears when you 'know' a project will fail even if the numbers say otherwise. She teaches us to trust 'hunches' as data processed at high speed by the limbic brain. She is the antidote to information overload; her lesson is Active Silence: withdrawing from the noise to listen to the internal truth.",
        3: "Fertile Creativity and Self-Care. The Empress alerts us against the 'Burnout Culture'. She teaches that rest is not laziness, but a vital part of the productive cycle. She is the defender of Conscious Pleasure. In work, she represents organic creativity: ideas that need to gestate without pressure. If you feel stuck, the Empress says: 'Stop pushing and start nourishing'. Connect with beauty or nature to reset your nervous system.",
        4: "Leadership and Inner Structure. The Emperor is not just 'the boss'; he is your own capacity for self-government. He represents Stoic Discipline. He appears to ask: 'Are you a slave to your impulses or king of your own mind?'. In modern life, it is the creation of systems and atomic habits that sustain long-term success. He teaches us to say 'No' to protect our time and energy. His lesson is that true freedom requires structure.",
        5: "The Mentor and Belonging. The Hierophant addresses our psychological need for belonging and shared meaning. He is the antidote to individualistic nihilism. In practice, he invites you to seek a mentor or a community of practice. He warns against 'Groupthink' but values Tradition as a library of time-tested solutions. He asks you: 'What do you believe in and who do you share that belief with?'.",
        6: "The Crossroads of Values and Emotional Intelligence. The Lovers pose the modern dilemma of 'Opportunity Cost'. Choosing A necessarily means killing B. Psychologically, it is the test of maturity: Do you choose based on Instant Gratification or your Core Values? In relationships, it warns against projection: seeing the other as a savior or a demon instead of a human being. It urges us to integrate head and heart to make irreversible decisions.",
        7: "Laser Focus and the Social Mask. The Chariot is the archetype of 'High Performance'. It speaks of the ability to compartmentalize emotions to achieve a goal ('Putting on the armor to go to work'). However, it warns of the danger of identifying too much with the social role (The Persona). It is victory through iron discipline, but remember: a chariot cannot be driven forever; the warrior eventually needs to rest.",
        8: "Resilience and Soft Power. Strength teaches us about Emotional Intelligence and self-regulation. In modern leadership, it is 'Soft Power': the ability to influence without forcing. It is vital for managing Productive Anger and turning conflict into creative fuel. If you feel exhausted from repressing your emotions, Strength invites you to dialogue with your 'inner beast' instead of caging it.",
        9: "Radical Introspection and the Inner Analyst. The Hermit invites you to disconnect to reconnect. It is the archetype of the 'Digital Detox' or the Silent Retreat. It appears when you need to filter out external noise to hear your own voice. Psychologically, it represents the ability to be alone without feeling lonely. It validates the need to move away from the crowd to find one's own truth.",
        10: "Locus of Control and Adaptability. The Wheel teaches us about Resilience in the face of change. In psychology, it is about understanding your 'Locus of Control': Do you focus on what you can change or complain about what you cannot? It is the arcanum of Stoicism. In finance and career, it represents market volatility. The lesson is: do not attach yourself to success nor define yourself by failure, both are phases of the cycle."
    },
    "pt": {
        0: "O Dispositor da Inovação e a Mente de Principiante. Na psicologia prática, O Louco nos convida a adotar a 'Shoshin' (Mente de Principiante) para curar a paralisia por análise. Não é apenas empreender um negócio, é a capacidade de operar com Confiança Radical diante da incerteza total. Representa a permissão interna para cometer erros como método de aprendizado iterativo. No seu dia a dia, aparece quando a lógica convencional diz 'pare', mas sua intuição grita 'pule'. É o antídoto contra o cinismo adulto; nos lembra que a brincadeira e a curiosidade são ferramentas de alta adaptação evolutiva, não distrações infantis.",
        1: "O Tecnólogo e a Autoeficácia. Psicologicamente, este arcano ativa sua Função Executiva: a capacidade de organizar, planejar e executar. É o estado de 'Deep Work' (Trabalho Profundo) onde a habilidade encontra o desafio, gerando o Estado de Fluxo. Aqui não há milagres; há Manifestação Consciente através da disciplina técnica. Em seus relacionamentos e carreira, O Mago pergunta: 'Você tem as ferramentas certas para o que quer construir?'. Nos ensina que a verdadeira magia é a atenção dirigida; onde você coloca seu foco, você coloca sua realidade.",
        2: "O Analista de Dados e a Intuição Estratégica. Na era da informação, a Sacerdotisa é o arquétipo da Intuição Estratégica. Não é magia, é o reconhecimento de padrões subconscientes. Ela aparece quando você 'sabe' que um projeto falhará, mesmo que os números digam o contrário. Ela nos ensina a confiar nos 'palpites' como dados processados em alta velocidade pelo cérebro límbico. É o antídoto para a saturação de informação; sua lição é o Silêncio Ativo: retirar-se do ruído para ouvir a verdade interna.",
        3: "Criatividade Fértil e Autocuidado. A Imperatriz nos alerta contra a 'Cultura do Burnout'. Ela ensina que o descanso não é preguiça, mas parte vital do ciclo produtivo. Ela é a defensora do Prazer Consciente. No trabalho, representa a criatividade orgânica: ideias que precisam gestar sem pressão. Se você se sentir estagnado, a Imperatriz diz: 'Pare de empurrar e comece a nutrir'. Conecte-se com a beleza ou a natureza para redefinir seu sistema nervoso.",
        4: "Liderança e Estrutura Interior. O Imperador não é apenas 'o chefe', é a sua própria capacidade de autogoverno. Representa a Disciplina Estoica. Ele aparece para perguntar: 'Você é escravo de seus impulsos ou rei de sua própria mente?'. Na vida moderna, é a criação de sistemas e hábitos atômicos que sustentam o sucesso a longo prazo. Ele nos ensina a dizer 'Não' para proteger nosso tempo e energia. Sua lição é que a verdadeira liberdade requer estrutura.",
        5: "O Mentor e o Pertencimento. O Hierofante aborda nossa necessidade psicológica de pertencimento e sentido compartilhado. É o antídoto contra o niilismo individualista. Na prática, ele convida você a buscar um mentor ou uma comunidade de prática. Ele adverte contra o 'Pensamento de Grupo' (Groupthink), mas valoriza a Tradição como uma biblioteca de soluções testadas pelo tempo. Ele lhe pergunta: 'No que você acredita e com quem você compartilha essa crença?'.",
        6: "A Encruzilhada de Valores e a Inteligência Emocional. Os Enamorados colocam o dilema moderno do 'Custo de Oportunidade'. Escolher A significa necessariamente matar B. Psicologicamente, é o teste de maturidade: Você escolhe com base na Gratificação Instantânea ou em seus Valores Nucleares? Nos relacionamentos, adverte contra a projeção: ver o outro como um salvador ou um demônio em vez de um ser humano. Nos impulsiona a integrar cabeça e coração para tomar decisões irreversíveis.",
        7: "Foco Laser e a Máscara Social. O Carro é o arquétipo do 'Alto Desempenho'. Fala sobre a capacidade de compartimentar emoções para alcançar um objetivo ('Vestir a armadura para ir trabalhar'). No entanto, adverte sobre o perigo de se identificar demais com o papel social (A Persona). É a vitória através da disciplina férrea, mas lembre-se: uma carruagem não pode ser conduzida para sempre; o guerreiro eventualmente precisa descansar.",
        8: "Resiliência e Soft Power. A Força nos ensina sobre Inteligência Emocional e autorregulação. Na liderança moderna, é o 'Soft Power': a capacidade de influenciar sem forçar. É vital para gerenciar a Raiva Produtiva e transformar o conflito em combustível criativo. Se você se sente exausto por reprimir suas emoções, A Força o convida a dialogar com sua 'fera interior' em vez de enjaulá-la.",
        9: "Introspecção Radical e o Analista Interno. O Eremita convida você a desconectar para reconectar. É o arquétipo do 'Detox Digital' ou do Retiro de Silêncio. Aparece quando você precisa filtrar o ruído externo para ouvir sua própria voz. Psicologicamente, representa a capacidade de estar só sem se sentir solitário. Valida a necessidade de afastar-se da massa para encontrar a própria verdade.",
        10: "Locus de Controle e Adaptabilidade. A Roda nos ensina sobre Resiliência diante da mudança. Na psicologia, trata-se de entender seu 'Locus de Controle': Você foca no que pode mudar ou reclama do que não pode? É o arcano do Estoicismo. Em finanças e carreira, representa a volatilidade do mercado. A lição é: não se apegue ao sucesso nem se defina pelo fracasso, ambas são fases do ciclo."
    }
}

print("Script ready. Add more translations for fr, de, ja, ko, zh as needed.")
print(f"Spanish source cards: {list(spanish_cotidiano.keys())}")
print(f"English translations: {list(translations['en'].keys())}")
print(f"Portuguese translations: {list(translations['pt'].keys())}")
