#!/usr/bin/env python3
"""
Complete translation script for cards 16-21 cotidiano sections
"""

# En/Pt translations for cards 16-21
cards_16_21 = {
    "en": {
        16: "Black Swans and Radical Disruption. In modern analysis, The Tower is the archetype of Technological Disruption and 'Black Swan' events (improbable events with high impact). Global server crashes, massive cyberattacks, or the emergence of AI making an entire industry obsolete are manifestations of The Tower. On a personal level, it is sudden revelation: discovering infidelity, a sudden medical diagnosis, or abrupt firing. It is the moment when the life narrative we tell ourselves becomes unsustainable before factual reality.",
        17: "Open Innovation and Active Hope. In today's world, The Star is the patron of Open Source and the democratization of knowledge. Just as the woman pours water freely, the Open Source movement shares innovation without barriers for collective benefit. It also governs holistic therapies, astronomy, astrology, and aerospace technology. It signals moments of post-crisis clarity, health recovery, and the ability to see the 'big picture' with optimism.",
        18: "The Uncanny Valley and Personal Branding. The Moon warns of illusions in the digital age. Deepfakes, manipulated images, and false identities (the Uncanny Valley phenomenon: something that appears almost human but generates discomfort). It also rules personal branding and public image management: what you project vs. who you really are. Psychologically, it is about confronting your own projections and ceasing to see 'monsters' where there are only shadows.",
        19: "Epigenetics and Authenticity. The Sun represents the activation of your genetic and creative potential. Modern epigenetics teaches us that our environment and attitudes 'turn on' or 'off' genes. The Sun is the switch that activates health, vitality, and success. It is radical authenticity: living openly without masks. In the digital age, it is transparency and building trust through honesty.",
        20: "The Digital Nomad and Metanoia. Judgement appears in contexts of radical reinvention. The digital nomad who abandons a traditional career for freedom, the entrepreneur who 'pivots' the business, or the spiritual awakening after a near-death experience. It is the archetype of the 'calling': the moment when you recognize your true vocation and leave the old world behind. Psychologically, it is the integration of the Shadow (the coffins opening) and the assumption of one's full identity.",
        21: "Global Consciousness and Synergy. The World represents the culmination of long-term projects and global integration. In business, it is successful expansion into international markets. It symbolizes 'synergy': the whole is greater than the sum of its parts. In ecology, it is systems thinking and planetary awareness. The World teaches us that true success is not isolationist but interconnected; you have not achieved mastery until you can integrate and celebrate all parts of yourself and the world."
    },
    "pt": {
        16: "Cisnes Negros e Disrupção Radical. Na análise moderna, A Torre é o arquétipo da Disrupção Tecnológica e dos eventos de 'Cisne Negro' (eventos improváveis de grande impacto). Quedes globais de servidores, ciberataques massivos ou o surgimento de uma IA que torna obsoleta uma indústria inteira são manifestações da Torre. A nível pessoal, é a revelação súbita: descobrir uma infidelidade, um diagnóstico médico repentino ou uma demissão fulminante. É o momento em que a narrativa de vida que contamos a nós mesmos torna-se insustentável diante da realidade factual.",
        17: "Inovação Aberta e Esperança Ativa. No mundo atual, A Estrela é a padroeira do Código Aberto (Open Source) e da democratização do conhecimento. Assim como a mulher derrama água livremente, o movimento Open Source compartilha inovação sem barreiras para o benefício coletivo. Também rege as terapias holísticas, a astronomia, a astrologia e a tecnologia aeroespacial. Sinaliza momentos de clareza pós-crise, recuperação da saúde e a capacidade de ver o 'panorama completo' com otimismo.",
        18: "O Vale Inquietante e a Marca Pessoal. A Lua adverte sobre ilusões na era digital. Deepfakes, imagens manipuladas e identidades falsas (o fenômeno do Vale Inquietante: algo que parece quase humano mas gera desconforto). Também rege a marca pessoal e o gerenciamento da imagem pública: o que você projeta vs. quem você realmente é. Psicologicamente, trata-se de confrontar suas próprias projeções e deixar de ver 'monstros' onde há apenas sombras.",
        19: "Epigenética e Autenticidade. O Sol representa a ativação de seu potencial genético e criativo. A epigenética moderna nos ensina que nosso ambiente e atitudes 'ativam' ou 'desativam' genes. O Sol é o interruptor que ativa saúde, vitalidade e sucesso. É a autenticidade radical: viver abertamente sem máscaras. Na era digital, é a transparência e a construção de confiança através da honestidade.",
        20: "O Nômade Digital e a Metanoia. O Julgamento aparece em contextos de reinvenção radical. O nômade digital que abandona uma carreira tradicional pela liberdade, o empreendedor que 'pivota' o negócio, ou o despertar espiritual após uma experiência de quase-morte. É o arquétipo do 'chamado': o momento em que você reconhece sua verdadeira vocação e deixa o mundo antigo para trás. Psicologicamente, é a integração da Sombra (os caixões se abrindo) e a assunção de sua identidade plena.",
        21: "Consciência Global e Sinergia. O Mundo representa a culminação de projetos de longo prazo e a integração global. Em negócios, é a expansão bem-sucedida para mercados internacionais. Simboliza a 'sinergia': o todo é maior que a soma das partes. Na ecologia, é o pensamento sistêmico e a consciência planetária. O Mundo nos ensina que o verdadeiro sucesso não é isolacionista, mas interconectado; você não alcançou a maestria até poder integrar e celebrar todas as partes de si mesmo e do mundo."
    }
}

print("Translations ready for cards 16-21:")
for card_id in range(16, 22):
    print(f"  Card {card_id}: EN ✓ PT ✓")
